IF
  Global("0403SecretDoor","AR0403",0)
  Global("KNOW_TIRESIAS","GLOBAL",2)
  // Note: [PC] target doesn't appear to work in door scripts. Using workaround.
  OR(6)
    Range(Player1,15)
    Range(Player2,15)
    Range(Player3,15)
    Range(Player4,15)
    Range(Player5,15)
    Range(Player6,15)
THEN
  RESPONSE #100
    SetGlobal("0403SecretDoor","AR0403",1)
    DetectSecretDoor("ar403d22")
END
